# -*- coding: utf-8 -*-
"""aula_06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iTJ4Yhtv0y-iUH9STLoCYSgnbzdYP2F2
"""

#-------------------------- AULA 06

# minha_lista = [9,2,583,4,55,88,77,14,5,8]  #Armazena maior quantidade de dados. Estrutura composta. Array
# print(minha_lista)
# print(minha_lista[2])

# primeiro_elemento = minha_lista[0]
# print(primeiro_elemento)

#----------------- MÉTODOS

#-----------  Adicionar itens a lista
# minha_lista.append('Alex')
# print(minha_lista)

#----------- Remove itens
# minha_lista.remove(2)  #REMOVE - Dados, indicar exatamente o valor que quer remover e ()
# print(minha_lista)

# del minha_lista[4] #DEL - Indice, pega pela posição e []
# print(minha_lista)

#----------- LEN Comprimento de uma lista, indices
# lista_dois = ['alex',5,8,17,498]
# lista4 = len(lista_dois)
# print(lista4)

#------------------------------- Looping com lista

# lista_cinco = [1,5,78,9,4,6,15,24,78]
# for i in lista_cinco: #Bloco de código
#   print(i)

#------------------------------- Lista Mista
#lista_mista = [1.5,5,'python', True]


#----------------------------------------------------------------------- EXERCÍCIOS

#Exercício 1: Crie uma lista chamada numeros que contenha os números inteiros de 1 a 5 e imprima-a na tela.
numeros = [1,2,3,4,5]
print(numeros)

# Exercício 2: Acesse e imprima o terceiro elemento da lista numeros.
print(numeros[2])

# Exercício 3: Adicione o número 6 à lista numeros e imprima a lista atualizada.
numeros.append(6)
print(numeros)

# Exercício 4: Remova o número 3 da lista numeros e imprima a lista resultante.
numeros.remove(3)
print(numeros)

# Exercício 5: Crie uma lista chamada frutas contendo três nomes de frutas diferentes. Em seguida, concatene essa lista com a lista numeros e imprima o resultado.
frutas = ['maça','banana','manga']
lista_combinado = numeros + frutas
print(lista_combinado)

# Exercício 6: Use um loop for para percorrer e imprimir todos os elementos da lista frutas.
for i in frutas:
    print(i)

# Exercício 7: Verifique se o número 5 está presente na lista numeros e imprima uma mensagem informando se ele está na lista ou não.
if 5 in numeros:
  print("O número 5 está na lista.") #Verdadeiro
else:
  print("O número 5 não está na lista.") #Falso